name: 'Andrea Radice: Teatro e Fotografia'
favicon: null
layout_spectrum: 0.24687
typography_spectrum: 0.00997951696626842
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5535714654251933
  lightness: 0.17449971823953092
  saturation: 0.7839331589639187
  rhythmicContrast: 0.6240779990330338
purpose: []
